eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762

spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Tomyangyi/blogs.git
          search-paths: configFile,configFile1,configFile2/test
          username: username
          password: password

