
server:
  port: 8763
  max-http-header-size: 10485760
  tomcat:
    uri-encoding: UTF-8

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: eurekaClient #定义项目的名称
  cloud:
    feign:
      hystrix:
        enabled: true
    ribbon:
      ReadTimeout: 10000
      ConnectTimeout: 10000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest