server:
  port: 8767
  max-http-header-size: 10485760
  tomcat:
    uri-encoding: UTF-8

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: kafkaClient
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.66.30:9092         #Kafka的消息中间件服务器
          zk-nodes: 192.168.66.30:2181        #Zookeeper的节点，如果集群，后面加,号分隔
          auto-create-topics: true        #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
      bindings:
        output:      #这里用stream给我们提供的默认output，后面会讲到自定义output
          destination: test    #消息发往的目的地
          content-type: text/plain    #消息发送的格式，接收端不用指定格式，但是发送端要
        input:
          destination: test    #消息发往的目的地
        input2:
          destination: test    #消息发往的目的地
