
server:
  port: 8764
  max-http-header-size: 10485760


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: eurekaClient #定义项目的名称
  cloud:
    feign:
      hystrix:
        enabled: true
zuul:
  routes:
    feign:
      path: /hello/**
      serviceId: feginClient